### ISSUE TITLE
Way to capture output (puts) inside sandbox

### ISSUE THREAD

**Issue by jwo** [omghax/jruby-sandbox#7]
I'd like to be able to capture and display the stdout used in the sandbox. Is this something I can access on the sandbox itself?

In regular ruby, I can do this to capture stdout.

```
    s = StringIO.new                                                                                                          
    $stdout = s
    result = yield
    @output = s.string
    result
  ensure
    $stdout = STDOUT
```

**Comment by adamfortuna** [comment]
Could do something like this for it:

```
require 'stringio'
def capture_stdout
  out = StringIO.new
  $stdout = out
  yield
  return out.string
ensure
  $stdout = STDOUT
end
```

Then whenever you want to run code with standard output, you can run it with 

```
sandbox.eval <<-RUBY
  capture_stdout do
    #{code}
  end
RUBY
```

**Comment by jwo** [comment]
FWIW, I was unable to do that --- I had to open up the Java classes to add an accessor to the stdOut stream: https://github.com/jwo/jruby-sandbox/commit/a6045c9c6770ecf4456b8b37b56887c33138a4ca

Since you weren't running into the problems, I doubted you'd want this upstream. But if you would, I can pull-request it for you.
